# Generated by Django 4.0.1 on 2022-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guidemenu_guidetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidemenu',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
