# Generated by Django 4.0.1 on 2022-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_guidemenu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemenu',
            name='slug',
            field=models.SlugField(),
        ),
    ]
