# Generated by Django 4.0.1 on 2022-06-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_guidemenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarelguide',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menuofguide', to='guide.guidemenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genarelguide',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='typeofguide', to='guide.guidetype'),
            preserve_default=False,
        ),
    ]
