# Generated by Django 4.0.1 on 2022-06-01 12:06

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_genarelguide_menu_genarelguide_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genarelguide',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
