# Generated by Django 4.0.1 on 2022-06-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_alter_genarelguide_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genarelguide',
            name='type',
        ),
        migrations.AddField(
            model_name='guidemenu',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='typeofguide', to='guide.guidetype'),
            preserve_default=False,
        ),
    ]
