# Generated by Django 4.0.1 on 2022-06-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_remove_genarelguide_type_guidemenu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetype',
            name='key',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
