# Generated by Django 4.0.1 on 2022-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_guidetype_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetype',
            name='icon_image',
            field=models.ImageField(default='', upload_to='guideicon/'),
            preserve_default=False,
        ),
    ]
