# Generated by Django 4.0.1 on 2022-06-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_guidetype_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidemenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuchild', to='guide.guidemenu'),
        ),
    ]
