# Generated by Django 4.0.1 on 2022-06-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_guidemenu_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidemenu',
            name='parent',
        ),
        migrations.AddField(
            model_name='genarelguide',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuchild', to='guide.genarelguide'),
        ),
    ]
