# Generated by Django 4.0.1 on 2022-06-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_remove_guidemenu_parent_genarelguide_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genarelguide',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuchild', to='guide.genarelguide'),
        ),
    ]
