# Generated by Django 4.0.1 on 2022-06-10 11:05

# import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_alter_genarelguide_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarelguide',
            name='content2',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
