# Generated by Django 4.0.1 on 2022-06-10 11:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_genarelguide_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genarelguide',
            name='content2',
        ),
        migrations.AlterField(
            model_name='genarelguide',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
