# Generated by Django 4.0.1 on 2022-06-10 11:16

# import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_remove_genarelguide_content2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genarelguide',
            name='content',
            field=models.TextField(),
        ),
    ]
