# Generated by Django 4.0.1 on 2022-08-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0015_alter_genarelguide_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarelguide',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidemenu',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidetype',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
