# Generated by Django 4.0.1 on 2023-01-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_genarelguide_position_guidemenu_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidemenu',
            old_name='type',
            new_name='guidetype',
        ),
    ]
