# Generated by Django 4.0.1 on 2023-03-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0017_rename_type_guidemenu_guidetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genarelguide',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menuchild', to='guide.genarelguide'),
        ),
    ]
