# Generated by Django 4.0.1 on 2022-03-21 10:03

import django.contrib.sites.managers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('doc', '0002_acordion_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExSite',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site', verbose_name='site')),
                ('site_meta', models.CharField(max_length=256)),
                ('site_description', models.TextField(max_length=500)),
                ('site_meta_tag', models.CharField(max_length=255)),
                ('site_favicon', models.ImageField(upload_to='site_image')),
                ('site_logo', models.ImageField(upload_to='site_image')),
                ('slogan', models.CharField(default='', max_length=150)),
                ('og_image', models.ImageField(upload_to='site_image')),
                ('mask_icon', models.FileField(upload_to='site_image', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=120)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
