# Generated by Django 4.0.1 on 2022-03-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_exsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exsite',
            name='site_meta_tag',
        ),
    ]
