# Generated by Django 4.0.1 on 2022-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_alter_acordion_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exsite',
            name='qualified_ans_range',
            field=models.IntegerField(default=1),
        ),
    ]
