# Generated by Django 4.0.1 on 2022-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0015_alter_acordion_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exsite',
            name='site_meta_tag',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
