# Generated by Django 4.0.1 on 2023-11-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf_cookies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='ip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='session_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
