# Generated by Django 4.0.1 on 2022-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
