# Generated by Django 4.0.1 on 2022-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usertype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
