# Generated by Django 4.0.1 on 2022-02-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usertype_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
