# Generated by Django 4.0.1 on 2022-02-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usertype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
