# Generated by Django 4.0.1 on 2022-02-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usertype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_consumer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
