# Generated by Django 4.0.1 on 2022-02-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usertype_is_consumer_usertype_is_expert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name'], 'permissions': (('can_access_usertype', 'Can access usertype'),)},
        ),
    ]
