# Generated by Django 4.0.1 on 2022-02-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0005_remove_evaluation_statement_genarated_and_more'),
        ('accounts', '0015_user_orgonization_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experts_in',
            field=models.ForeignKey(blank=True, limit_choices_to={'common_status': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_label', to='evaluation.difinedlabel'),
        ),
    ]
