# Generated by Django 4.0.1 on 2022-02-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_experts_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='active',
            field=models.CharField(default='disabled', max_length=15),
        ),
        migrations.AddField(
            model_name='usertype',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
