# Generated by Django 4.0.1 on 2022-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_usertype_active_usertype_sort_order'),
    ]

    operations = [
        
    ]
