# Generated by Django 4.0.1 on 2022-03-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_usertype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='term_agree',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail Address'),
        ),
    ]
