# Generated by Django 4.0.1 on 2022-03-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_term_agree_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='term_agree',
            field=models.BooleanField(),
        ),
    ]
