# Generated by Django 4.0.1 on 2022-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_usertype_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
