# Generated by Django 4.0.1 on 2022-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_usertype_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
