# Generated by Django 4.0.1 on 2022-04-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_usertype_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['sort_order'], 'permissions': (('can_access_usertype', 'Can access usertype'),)},
        ),
    ]
