# Generated by Django 4.0.1 on 2022-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_usertype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_marine',
            field=models.BooleanField(default=False),
        ),
    ]
