# Generated by Django 4.0.1 on 2022-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_profile_established'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
    ]
