# Generated by Django 4.0.1 on 2022-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_profile_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
