# Generated by Django 4.0.1 on 2023-02-16 15:52

import accounts.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_user_options_profile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters and numbers only.', max_length=150, unique=True, validators=[accounts.helper.CustomsernameValidator()], verbose_name='username'),
        ),
    ]
