# Generated by Django 4.0.1 on 2023-03-17 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0103_alter_evaluator_options_and_more'),
        ('accounts', '0037_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNextActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_activities', to='evaluation.nextactivities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_next_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
