# Generated by Django 4.0.1 on 2023-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
    ]
