# Generated by Django 4.0.1 on 2023-04-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_profile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usertype', to='accounts.usertype'),
        ),
    ]
