# Generated by Django 4.0.1 on 2023-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orgonization',
            field=models.CharField(blank=True, max_length=252, null=True, verbose_name='Organization'),
        ),
    ]
