# Generated by Django 4.0.1 on 2023-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_user_orgonization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orgonization',
            field=models.CharField(max_length=252, verbose_name='Organization'),
        ),
    ]
