# Generated by Django 4.0.1 on 2023-05-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_user_orgonization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If true profile data visible to logged in other users of the platform.', verbose_name='Profile is Public'),
        ),
    ]
