# Generated by Django 4.0.1 on 2023-09-26 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_user_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('marketing_mail', models.BooleanField(default=True)),
                ('new_fuel_notifications', models.BooleanField(default=True)),
                ('blog_notifications', models.BooleanField(default=True)),
            ],
        ),
    ]
