# Generated by Django 4.0.1 on 2022-08-01 11:20

from django.db import migrations, models
import django.utils.timezone
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0003_alter_blogpost_author_alter_blogpost_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
