# Generated by Django 4.0.1 on 2023-08-30 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('content_type', 'object_id', 'user', 'action_type')},
        ),
    ]
