# Generated by Django 4.0.1 on 2022-04-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0036_question_chapter_name'),
        ('home', '0004_remove_quotation_related_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='related_questions',
            field=models.ManyToManyField(help_text='Help Text will go here', limit_choices_to={'is_active': True}, to='evaluation.Question', verbose_name='Please select all other question which are also tested within the provided quotation'),
        ),
    ]
