# Generated by Django 4.0.1 on 2022-04-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_quotation_test_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='require_documents',
        ),
        migrations.AddField(
            model_name='quotation',
            name='require_documents',
            field=models.ManyToManyField(help_text='Help Text will go', related_name='requiredocuments', to='home.QuotationDocType', verbose_name='Document needed for test'),
        ),
    ]
