# Generated by Django 4.0.1 on 2022-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0037_nextactivities'),
        ('home', '0011_remove_quotation_require_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='related_questions',
            field=models.ManyToManyField(help_text='Allow multiple option selection. The selected options should be highlighted.', limit_choices_to={'is_active': True, 'is_door': False}, to='evaluation.Question', verbose_name='Please select all other question which are also tested within the provided quotation'),
        ),
    ]
