# Generated by Django 4.0.1 on 2022-06-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0056_evaluator_feedback_updated'),
        ('home', '0012_alter_quotation_related_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='next_activities',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotnextactivity', to='evaluation.nextactivities'),
        ),
    ]
