# Generated by Django 4.0.1 on 2022-06-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0056_evaluator_feedback_updated'),
        ('home', '0013_quotation_next_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='next_activities',
            field=models.ForeignKey(blank=True, help_text='Select next activities to select related questions from next activities', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotnextactivity', to='evaluation.nextactivities'),
        ),
    ]
