# Generated by Django 4.0.1 on 2022-06-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_quotation_next_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='comments',
            field=models.TextField(blank=True, help_text='This field will take charecter upto 500', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='display_site_address',
            field=models.BooleanField(default=True, help_text='Tick will display system address IO Validation partner address'),
        ),
    ]
