# Generated by Django 4.0.1 on 2022-06-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_quotation_comments_quotation_display_site_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='display_site_address',
            field=models.BooleanField(default=True, help_text='Tick will display system address IO Validation partner address', verbose_name='Display Site Address'),
        ),
    ]
