# Generated by Django 4.0.1 on 2022-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_quotation_display_site_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='factory_pickup',
            field=models.BooleanField(help_text='Place a tick mark to indicate whether the sample will be collected from the factory.', verbose_name='Factory Sample pick-up'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='needy_time',
            field=models.IntegerField(help_text='Write the proper needy time to conduct the test and remember to choose the appropriate time unit from the options next to the needy time box.', verbose_name='Total needed time for the test'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Write the proper price and remember to choose the appropriate pricing unit from the options next to the price box.', max_digits=10, verbose_name='Quotation Price'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='require_documents',
            field=models.ManyToManyField(help_text='Select the documents you need to perform this test. Can select multiple. Hold down “Control”, or “Command” on a Mac, to select more than one.', related_name='requiredocuments', to='home.QuotationDocType', verbose_name='Document needed for test'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sample_amount',
            field=models.IntegerField(help_text='Note how much sample you need to perform this test. Do not forget to select the unit of weight.', verbose_name='Sample amount needed for test'),
        ),
    ]
