# Generated by Django 4.0.1 on 2022-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_quotation_factory_pickup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceunit',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weightunit',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
