# Generated by Django 4.0.1 on 2022-10-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_priceunit_name_alter_timeunit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='show_alternate_business',
            field=models.CharField(blank=True, help_text='You can show alternate email address in quotation.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='show_alternate_email',
            field=models.EmailField(blank=True, help_text='You can show alternate email address in quotation.', max_length=254, null=True),
        ),
    ]
