# Generated by Django 4.0.1 on 2022-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_quotation_show_alternate_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='show_alternate_phone',
            field=models.CharField(blank=True, help_text='You can show alternate phone number in quotation.', max_length=50, null=True),
        ),
    ]
