# Generated by Django 4.0.1 on 2023-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_quotation_show_alternate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='require_documents',
            field=models.ManyToManyField(help_text='Select the documents that are needed to perform this test. You can select multiple in mac by holding shift + command and down arrow and in windows ctrl/shift + down arrow.', related_name='requiredocuments', to='home.QuotationDocType', verbose_name='Document needed for test'),
        ),
    ]
