# Generated by Django 4.0.1 on 2023-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0107_alter_evalebelstatement_question'),
        ('home', '0021_alter_quotation_require_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='related_questions',
            field=models.ManyToManyField(help_text='Allow multiple option selection. The selected options should be highlighted.', limit_choices_to={'is_active': True, 'is_door': False}, related_name='quotations_related_questions', to='evaluation.Question', verbose_name='Please select all other question which are also tested within the provided quotation'),
        ),
    ]
