# Generated by Django 4.0.1 on 2023-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0111_alter_evalebelstatement_dont_know_and_more'),
        ('home', '0022_alter_quotation_related_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='related_questions',
            field=models.ManyToManyField(db_index=True, help_text='Allow multiple option selection. The selected options should be highlighted.', limit_choices_to={'is_active': True, 'is_door': False}, related_name='quotations_related_questions', to='evaluation.Question', verbose_name='Please select all other question which are also tested within the provided quotation'),
        ),
    ]
