# Generated by Django 4.0.1 on 2022-12-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('anchor', models.SlugField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['title', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='glossary.glossary')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedlinks', to='glossary.glossary')),
            ],
        ),
    ]
