# Generated by Django 4.0.1 on 2022-12-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
