# Generated by Django 4.0.1 on 2022-12-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_delete_synonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='anchor',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
