# Generated by Django 4.0.1 on 2023-01-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_grequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grequests',
            options={'verbose_name': 'G Request', 'verbose_name_plural': 'G Requests'},
        ),
    ]
