# Generated by Django 4.0.1 on 2022-02-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crm',
            new_name='Lead',
        ),
    ]
