# Generated by Django 4.0.1 on 2022-02-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_crm_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
