# Generated by Django 4.0.1 on 2022-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
