# Generated by Django 4.0.1 on 2022-02-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_confirm_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='pnone',
            new_name='phone',
        ),
    ]
