# Generated by Django 4.0.1 on 2022-02-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_pnone_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='134175144764', max_length=50),
        ),
    ]
