# Generated by Django 4.0.1 on 2022-02-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='044215291296', max_length=50),
        ),
    ]
