# Generated by Django 4.0.1 on 2022-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_lead_confirm_code_alter_mailqueue_process_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='289806495651', max_length=50),
        ),
    ]
