# Generated by Django 4.0.1 on 2022-05-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0093_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='997270337635', max_length=50),
        ),
    ]
