# Generated by Django 4.0.1 on 2022-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0103_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='925640493302', max_length=50),
        ),
    ]
