# Generated by Django 4.0.1 on 2022-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0144_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='653871061931', max_length=50),
        ),
    ]
