# Generated by Django 4.0.1 on 2022-08-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0152_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='341207259731', max_length=50),
        ),
    ]
