# Generated by Django 4.0.1 on 2022-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0158_alter_lead_confirm_code_alter_lead_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='190087087980', max_length=50),
        ),
    ]
