# Generated by Django 4.0.1 on 2022-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0160_alter_lead_confirm_code_blogmailqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='934382826559', max_length=50),
        ),
    ]
