# Generated by Django 4.0.1 on 2022-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0165_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='539895396961', max_length=50),
        ),
    ]
