# Generated by Django 4.0.1 on 2022-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0203_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='804415719187', max_length=50),
        ),
    ]
