# Generated by Django 4.0.1 on 2023-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0238_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='295902135960', max_length=50),
        ),
    ]
