# Generated by Django 4.0.1 on 2023-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0242_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='657901613447', max_length=50),
        ),
    ]
