# Generated by Django 4.0.1 on 2023-04-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0246_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='942331720918', max_length=50),
        ),
    ]
