# Generated by Django 4.0.1 on 2023-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0253_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='846545915900', max_length=50),
        ),
    ]
