# Generated by Django 4.0.1 on 2023-06-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0254_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='312006722633', max_length=50),
        ),
    ]
