# Generated by Django 4.0.1 on 2023-09-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0269_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerMailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=256, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('process_time', models.DateTimeField(auto_now=True)),
                ('tried', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='263116768692', max_length=50),
        ),
    ]
