# Generated by Django 4.0.1 on 2023-09-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0270_consumermailqueue_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumerMailQueue',
        ),
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='304288723652', max_length=50),
        ),
    ]
