# Generated by Django 4.0.1 on 2023-09-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0114_alter_evaluator_make_it_public'),
        ('crm', '0271_delete_consumermailqueue_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='052193668785', max_length=50),
        ),
        migrations.CreateModel(
            name='ConsumerMailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=256, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('process_time', models.DateTimeField(auto_now=True)),
                ('tried', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.evaluator')),
            ],
        ),
    ]
