# Generated by Django 4.0.1 on 2023-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0272_alter_lead_confirm_code_consumermailqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='229606283869', max_length=50),
        ),
    ]
