# Generated by Django 4.0.1 on 2023-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0278_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='601036245148', max_length=50),
        ),
    ]
