# Generated by Django 4.0.1 on 2023-10-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0279_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='212129239165', max_length=50),
        ),
    ]
