# Generated by Django 4.0.1 on 2023-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0280_alter_lead_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confirm_code',
            field=models.CharField(default='406868375621', max_length=50),
        ),
    ]
